var photoPosts=new Array();

var photoPostsSource = [
    {
        id:'1',
        name:'АЦЦ',
        country:'Германия',
        dosage:'300-400 мг/день',
        price:'10',
        description:'Таблетки шипучие белого цвета, круглые, плоскоцилиндрические. Применяется при в заболеваниях органов дыхания, сопровождающихся образованием густой и трудноотделяемой мокроты.',
        author:'Иванов Иван',
        photoLink:'https://skorohod-nn.ru/wp-content/uploads/5/3/3/533d44aaf0a7a16d3ab4e550133dba9b.jpeg',
        createdAt: new Date('2015-07-23T23:00:00'),
    },
    {
        id:'2',
        name:'Аллеркапс',
        country:'Беларусь',
        dosage:'10 мг/день',
        price:'3',
        description:'Капсулы твердые желатиновые цилиндрической формы с полусферическими концами белого цвета. Применяется для снятия симптомов аллергических реакций.',
        author:'Сергей Михайлович',
        photoLink:'https://med-advisor.ru/wp-content/uploads/2018/10/allergiya-na-funduk3-768x512.png',
        createdAt: new Date('2015-08-23T15:24:02'),

    },
    {
        id:'3',
        name:'Арпетол',
        country:'Беларусь',
        dosage:'200 мг/день',
        price:'10',
        description:'Таблетки, покрытые оболочкой, белого цвета. Применяется для профилактики и лечения: грипп А и В, и другие ОРВИ.',
        author:'Иванов Иван',
        photoLink:'https://clinica-opora.ru/wp-content/uploads/2021/02/d0b0d180d0b1d0b8d0b4d0bed0bb-d0b2-1-2-d0b8-3-d182d180d0b8d0bcd0b5d181d182d180d0b0d185-d0b1d0b5d180d0b5d0bcd0b5d0bdd0bdd0bed181d182d0b8_601b0300d310b.png',
        createdAt: new Date('2019-01-03T21:00:00'),

    },
    {
        id:'4',
        name:'Тропикамид',
        country:'Румыния',
        dosage:'1-2 капли',
        price:'5',
        description:'Прозрачный бесцветный раствор. Применяется как мидриатик и циклоплегик, показанный для диагностических целей и в пред-и послеоперационных состояниях.',
        author:'Света Олеговна',
        photoLink:'http://lekhar.ru/wp-content/uploads/2018/01/tropikamid-1.png',
        createdAt: new Date('2019-11-15T08:13:00'),
    },
    {
        id:'5',
        name:'Маалокс',
        country:'Италия',
        dosage:'4-6 табл/день',
        price:'10',
        description:'Таблетки белого цвета круглые, плоские, со скошенными краями, с гравировкой «Мх» с обеих сторон. Применяется для антацидной терапии при изжоге и гастроэзофагальном рефлюксе у пациентов старше 15 лет.',
        author:'Эвелина Хавьеровна',
        photoLink:'https://vseglisty.ru/wp-content/uploads/9/f/5/9f58e36729a5a2c9b320a586b2374e51.jpg',
        createdAt: new Date('2015-08-23T15:24:02'),
    },
    {
            id:'6',
            name:'АЦЦ',
            country:'Германия',
            dosage:'300-400 мг/день',
            price:'10',
            description:'Таблетки шипучие белого цвета, круглые, плоскоцилиндрические. Применяется при в заболеваниях органов дыхания, сопровождающихся образованием густой и трудноотделяемой мокроты.',
            author:'Иванов Иван',
            photoLink:'https://skorohod-nn.ru/wp-content/uploads/5/3/3/533d44aaf0a7a16d3ab4e550133dba9b.jpeg',
            createdAt: new Date('2015-07-23T23:00:00'),
      },
     {
            id:'7',
            name:'Аллеркапс',
            country:'Беларусь',
            dosage:'10 мг/день',
            price:'3',
            description:'Капсулы твердые желатиновые цилиндрической формы с полусферическими концами белого цвета. Применяется для снятия симптомов аллергических реакций.',
            author:'Сергей Михайлович',
            photoLink:'https://med-advisor.ru/wp-content/uploads/2018/10/allergiya-na-funduk3-768x512.png',
            createdAt: new Date('2015-08-23T15:24:02'),

        },
        {
            id:'8',
            name:'Арпетол',
            country:'Беларусь',
            dosage:'200 мг/день',
            price:'10',
            description:'Таблетки, покрытые оболочкой, белого цвета. Применяется для профилактики и лечения: грипп А и В, и другие ОРВИ.',
            author:'Иванов Иван',
            photoLink:'https://clinica-opora.ru/wp-content/uploads/2021/02/d0b0d180d0b1d0b8d0b4d0bed0bb-d0b2-1-2-d0b8-3-d182d180d0b8d0bcd0b5d181d182d180d0b0d185-d0b1d0b5d180d0b5d0bcd0b5d0bdd0bdd0bed181d182d0b8_601b0300d310b.png',
            createdAt: new Date('2019-01-03T21:00:00'),

        },
        {
            id:'9',
            name:'Тропикамид',
            country:'Румыния',
            dosage:'1-2 капли',
            price:'5',
            description:'Прозрачный бесцветный раствор. Применяется как мидриатик и циклоплегик, показанный для диагностических целей и в пред-и послеоперационных состояниях.',
            author:'Света Олеговна',
            photoLink:'http://lekhar.ru/wp-content/uploads/2018/01/tropikamid-1.png',
            createdAt: new Date('2019-11-15T08:13:00'),
        },
        {
            id:'10',
            name:'Маалокс',
            country:'Италия',
            dosage:'4-6 табл/день',
            price:'10',
            description:'Таблетки белого цвета круглые, плоские, со скошенными краями, с гравировкой «Мх» с обеих сторон. Применяется для антацидной терапии при изжоге и гастроэзофагальном рефлюксе у пациентов старше 15 лет.',
            author:'Эвелина Хавьеровна',
            photoLink:'https://vseglisty.ru/wp-content/uploads/9/f/5/9f58e36729a5a2c9b320a586b2374e51.jpg',
            createdAt: new Date('2015-08-23T15:24:02'),
        },
     {
           id:'11',
           name:'АЦЦ',
           country:'Германия',
           dosage:'300-400 мг/день',
           price:'10',
           description:'Таблетки шипучие белого цвета, круглые, плоскоцилиндрические. Применяется при в заболеваниях органов дыхания, сопровождающихся образованием густой и трудноотделяемой мокроты.',
           author:'Иванов Иван',
           photoLink:'https://skorohod-nn.ru/wp-content/uploads/5/3/3/533d44aaf0a7a16d3ab4e550133dba9b.jpeg',
           createdAt: new Date('2015-07-23T23:00:00'),
       },
       {
           id:'12',
           name:'Аллеркапс',
           country:'Беларусь',
           dosage:'10 мг/день',
           price:'3',
           description:'Капсулы твердые желатиновые цилиндрической формы с полусферическими концами белого цвета. Применяется для снятия симптомов аллергических реакций.',
           author:'Сергей Михайлович',
           photoLink:'https://med-advisor.ru/wp-content/uploads/2018/10/allergiya-na-funduk3-768x512.png',
           createdAt: new Date('2015-08-23T15:24:02'),

       },
       {
           id:'13',
           name:'Арпетол',
           country:'Беларусь',
           dosage:'200 мг/день',
           price:'10',
           description:'Таблетки, покрытые оболочкой, белого цвета. Применяется для профилактики и лечения: грипп А и В, и другие ОРВИ.',
           author:'Иванов Иван',
           photoLink:'https://clinica-opora.ru/wp-content/uploads/2021/02/d0b0d180d0b1d0b8d0b4d0bed0bb-d0b2-1-2-d0b8-3-d182d180d0b8d0bcd0b5d181d182d180d0b0d185-d0b1d0b5d180d0b5d0bcd0b5d0bdd0bdd0bed181d182d0b8_601b0300d310b.png',
           createdAt: new Date('2019-01-03T21:00:00'),

       },
       {
           id:'14',
           name:'Тропикамид',
           country:'Румыния',
           dosage:'1-2 капли',
           price:'5',
           description:'Прозрачный бесцветный раствор. Применяется как мидриатик и циклоплегик, показанный для диагностических целей и в пред-и послеоперационных состояниях.',
           author:'Света Олеговна',
           photoLink:'http://lekhar.ru/wp-content/uploads/2018/01/tropikamid-1.png',
           createdAt: new Date('2019-11-15T08:13:00'),
       },
       {
           id:'15',
           name:'Маалокс',
           country:'Италия',
           dosage:'4-6 табл/день',
           price:'10',
           description:'Таблетки белого цвета круглые, плоские, со скошенными краями, с гравировкой «Мх» с обеих сторон. Применяется для антацидной терапии при изжоге и гастроэзофагальном рефлюксе у пациентов старше 15 лет.',
           author:'Эвелина Хавьеровна',
           photoLink:'https://vseglisty.ru/wp-content/uploads/9/f/5/9f58e36729a5a2c9b320a586b2374e51.jpg',
           createdAt: new Date('2015-08-23T15:24:02'),
       },
       {
             id:'16',
             name:'АЦЦ',
             country:'Германия',
             dosage:'300-400 мг/день',
             price:'10',
             description:'Таблетки шипучие белого цвета, круглые, плоскоцилиндрические. Применяется при в заболеваниях органов дыхания, сопровождающихся образованием густой и трудноотделяемой мокроты.',
             author:'Иванов Иван',
             photoLink:'https://skorohod-nn.ru/wp-content/uploads/5/3/3/533d44aaf0a7a16d3ab4e550133dba9b.jpeg',
             createdAt: new Date('2015-07-23T23:00:00'),
         },
         {
             id:'17',
             name:'Аллеркапс',
             country:'Беларусь',
             dosage:'10 мг/день',
             price:'3',
             description:'Капсулы твердые желатиновые цилиндрической формы с полусферическими концами белого цвета. Применяется для снятия симптомов аллергических реакций.',
             author:'Сергей Михайлович',
             photoLink:'https://med-advisor.ru/wp-content/uploads/2018/10/allergiya-na-funduk3-768x512.png',
             createdAt: new Date('2015-08-23T15:24:02'),

         },
         {
             id:'18',
             name:'Арпетол',
             country:'Беларусь',
             dosage:'200 мг/день',
             price:'10',
             description:'Таблетки, покрытые оболочкой, белого цвета. Применяется для профилактики и лечения: грипп А и В, и другие ОРВИ.',
             author:'Иванов Иван',
             photoLink:'https://clinica-opora.ru/wp-content/uploads/2021/02/d0b0d180d0b1d0b8d0b4d0bed0bb-d0b2-1-2-d0b8-3-d182d180d0b8d0bcd0b5d181d182d180d0b0d185-d0b1d0b5d180d0b5d0bcd0b5d0bdd0bdd0bed181d182d0b8_601b0300d310b.png',
             createdAt: new Date('2019-01-03T21:00:00'),

         },
         {
             id:'19',
             name:'Тропикамид',
             country:'Румыния',
             dosage:'1-2 капли',
             price:'5',
             description:'Прозрачный бесцветный раствор. Применяется как мидриатик и циклоплегик, показанный для диагностических целей и в пред-и послеоперационных состояниях.',
             author:'Света Олеговна',
             photoLink:'http://lekhar.ru/wp-content/uploads/2018/01/tropikamid-1.png',
             createdAt: new Date('2019-11-15T08:13:00'),
         },
         {
             id:'20',
             name:'Маалокс',
             country:'Италия',
             dosage:'4-6 табл/день',
             price:'10',
             description:'Таблетки белого цвета круглые, плоские, со скошенными краями, с гравировкой «Мх» с обеих сторон. Применяется для антацидной терапии при изжоге и гастроэзофагальном рефлюксе у пациентов старше 15 лет.',
             author:'Эвелина Хавьеровна',
             photoLink:'https://vseglisty.ru/wp-content/uploads/9/f/5/9f58e36729a5a2c9b320a586b2374e51.jpg',
             createdAt: new Date('2015-08-23T15:24:02'),
         },

];

var ArrOfNames=['АЦЦ','Арпетол','Аллеркапс','Маалокс','Тропикамид'];
var ArrOfNames=['Эвелина Хавьеровна','Света Олеговна','Иванов Иван','Сергей Михайлович'];
